steps:
- type: SubworkflowStep
  parameters:
  - name: Subworkflow
    type: Value
    value: "sub1"
  - name: myVariable
    type: Value
    value: 00:00:10

- type: SubworkflowStep
  parameters:
  - name: Subworkflow
    type: Value
    value: "sub1"
  - name: myVariable
    type: Value
    value: 00:00:04

subworkflows:
  sub1:
    variables:
    - name: myVariable
      unit: sec
      variableType: Argument
      dataType: TimeParameter
      value: 00:00:03
    steps:
    - type: WaitStep
      parameters:
      - name: Time
        type: Variable
        value: myVariable
