steps:
- type: SubworkflowStep
  parameters:
  - name: Subworkflow
    type: Value
    value: "sub1"
  - name: myVariable
    type: Value
    value: 00:00:02

- type: SubworkflowStep
  parameters:
  - name: Subworkflow
    type: Value
    value: "sub1"
  - name: myVariable
    type: Value
    value: 00:00:04

- type: LoopStep
  parameters:
  - name: IterationCount
    type: Value
    value: 2
  children:
  - type: WaitStep
    parameters:
    - name: Time
      type: Value
      value: 00:00:01

subworkflows:
  sub1:
    variables:
    - name: myVariable
      unit: sec
      variableType: Argument
      dataType: TimeParameter
      value: 00:00:03
    steps:
    - type: WaitStep
      parameters:
      - name: Time
        type: Variable
        value: myVariable
