steps:
- type: SubworkflowStep
  parameters:
  - name: Subworkflow
    type: Value
    value: "sub1"
  - name: myVariable
    type: Value
    value: 2

- type: LoopStep
  parameters:
  - name: IterationCount
    type: Value
    value: 2
  children:
  - type: SubworkflowStep
    parameters:
    - name: Subworkflow
      type: Value
      value: "sub1"
    - name: myVariable
      type: Value
      value: 2

subworkflows:
  sub1:
    variables:
    - name: myVariable
      unit: sec
      variableType: Argument
      dataType: IntParameter
      value: 2
    steps:
    - type: WaitStep
      parameters:
      - name: Time
        type: Variable
        value: myVariable
