[[components]]
id = "my-component"
name = "my-component"
type = "wago-bus"
parameters = [
    { name = "ip-address", value = "127.0.0.1" },
]

[[components]]
id = "my-component-child"
name = "my-component-child"
type = "wago-ao"
parameters = [
    { name = "address", value = "1" },
    { name = "gain", value="1" },
    { name = "offset", value="0" },
    { name = "unit", value="mV" },
]

[[components]]
id = "my-component-child2"
name = "my-component-child2"
type = "wago-ao"
parameters = [
    { name = "address", value = "2" },
    { name = "gain", value="1" },
    { name = "offset", value="0" },
    { name = "unit", value="mV" },
]

[[components]]
id = "my-component-2"
name = "my-component-2"
type = "usv"
